/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RaceRouteImport } from './routes/race'
import { Route as CircuitsIndexRouteImport } from './routes/circuits.index'
import { Route as CircuitsSlugRouteImport } from './routes/circuits.$slug'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceRoute = RaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsIndexRoute = CircuitsIndexRouteImport.update({
  id: '/circuits/',
  path: '/circuits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsSlugRoute = CircuitsSlugRouteImport.update({
  id: '/circuits/$slug',
  path: '/circuits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/race': typeof RaceRoute
  '/circuits/$slug': typeof CircuitsSlugRoute
  '/circuits/': typeof CircuitsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/race': typeof RaceRoute
  '/circuits/$slug': typeof CircuitsSlugRoute
  '/circuits': typeof CircuitsIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/race': typeof RaceRoute
  '/circuits/$slug': typeof CircuitsSlugRoute
  '/circuits/': typeof CircuitsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/race' | '/circuits/$slug' | '/circuits/' | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/race' | '/circuits/$slug' | '/circuits' | '/teams'
  id: '__root__' | '/' | '/race' | '/circuits/$slug' | '/circuits/' | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RaceRoute: typeof RaceRoute
  CircuitsSlugRoute: typeof CircuitsSlugRoute
  CircuitsIndexRoute: typeof CircuitsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race': {
      id: '/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof RaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits/': {
      id: '/circuits/'
      path: '/circuits'
      fullPath: '/circuits/'
      preLoaderRoute: typeof CircuitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits/$slug': {
      id: '/circuits/$slug'
      path: '/circuits/$slug'
      fullPath: '/circuits/$slug'
      preLoaderRoute: typeof CircuitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RaceRoute: RaceRoute,
  CircuitsSlugRoute: CircuitsSlugRoute,
  CircuitsIndexRoute: CircuitsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
